version: "3"
services:
  backend:
    build: ./server
    ports:
      - 5012:5012
      - 443:443
      - 80:80
    extra_hosts:
      - localhost:host-gateway
  frontend:
    build: ./client
    ports:
      - 8080:8080
